[package]
name = "jumpcutter-rs"
version = "0.1.0"
authors = ["Sebastian Steiner <sebastian.steiner@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
